### ISSUE TITLE
Refactor Telemetry code from Hotpot

### ISSUE THREAD

**Issue by kumarashit** [sodafoundation/api#1248]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
/kind feature

**What happened**:

**What you expected to happen**:
Refactor and separate Telemetry code from Hotpot

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Hotpot(release/branch) version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by NajmudheenCT** [comment]
Refactor discussion with @PravinRanjan10 @neelam on 3/16/2020 MOM
--------------
1. sperated private repo is able to build and test
2. Pravin has refined the code , ( removed unwated reference to pool and volume interfaces, which was in hotpot)
3. Pravin to check imapct of havin shared keystone service, make it work for telemtry when hotpot is there ort not there
4. Pravin to check impact of having dedicated etcd db ( exisitng is shared by hotpot)
5. Pravin to check impact of changing REST and grpc endpoints
6. Neelam to complete installer separation , and then to start on separation of CI part

**Comment by kumarashit** [comment]
Not required as of now. We will re-visit if required
