### ISSUE TITLE
soda:api Make installation smooth by enhancing the wiki doc

### ISSUE THREAD

**Issue by PravinRanjan10** [sodafoundation/api#1292]
**Issue/Feature Description:**

**Why this issue to fixed / feature is needed(give scenarios or use cases):**
1. soda:api Make installation smooth by enhancing the wiki doc. Following steps need to be added in "soda:api Make installation smooth by enhancing the wiki doc" i.e developer environment

* installing steps for: go, docker, git   (this can be copied from ansible wiki steps)
* make or make all before install.sh script
* We need to add the steps to make sure, controller and dock binaries are there
* grpc version need to be corrected. 
* correct path for osdsctl 

**How to reproduce, in case of a bug:**

**Other Notes /  Environment Information: (Please give the env information, log link or any useful information for this issue)**

**Comment by kumarashit** [comment]
https://github.com/sodafoundation/api/wiki/SODA-core-projects-Local-Cluster-with-Multi-tenants-Installation

**Comment by kumarashit** [comment]
The request has been updated. Changed the wiki
