### ISSUE TITLE
Update the project to  GO 1.18

### ISSUE THREAD

**Issue by shelar1423** [sodafoundation/api#1323]
Issue/Feature Description:
Update the project to compile and build using GO 1.18 

Why this issue to fixed / feature is needed(give scenarios or use cases):
This issue is required to comply the project with latest stable version of Go

**Comment by shelar1423** [comment]
@asifdxtreme  kindly label sodacode2022 and sodamid

**Comment by shelar1423** [comment]
@asifdxtreme

**Comment by asifdxtreme** [comment]
> @asifdxtreme

Done, Thanks

**Comment by shelar1423** [comment]
@asifdxtreme so this issue is accepted for my sodacode contribution right?
